### ISSUE TITLE
Registration process glitch

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#106] opened 2021-05-21 10:10 UTC
A user has reported this:

> I filled in Create New Account with Captcha, and was then presented with a page headed "Resolve multiple users". This said it needed to check which other sites I log into. I was presented, on the same page a list, each with a tick box: UKBMS, Moth Night, iRecord.
> 
> I ticked them all as true and pressed the only button: Save. The system then hung and eventually timed out. I have not tried to do anything else, because I assumed I had failed.

As far as I can see the registration with PoMS did complete successfully, and the website links have all been made for the user account in the warehouse (user ID 177). So there may be no action needed, but it is unhelpful if the system is timing out and making it look like it hasn't completed the registration process.

**Comment by BirenRathod** [comment] 2021-05-21 10:13
@kitenetter This is indicia problem. This has resolved in other website by John. So it needs to look into by @andrewvanbreda. I assigned this to him.

**Comment by andrewvanbreda** [comment] 2021-05-21 10:28
@BirenRathod @kitenetter 
Um......it sounds like actually the warehouse part is hanging. It may even be just caught warehouse at bad time. As it has linked the ID, it seems likely to me it is the warehouse end that had the problem.
I will see if I can think of way to reproduce the scenario and make sure it runs ok.
It is as it says when there are several ambiguous accounts to resolve against.
This situation shouldn't happen often.

**Comment by andrewvanbreda** [comment] 2021-06-08 09:52
@kitenetter 
I have investigated this issue.
I think I will have to close this and put it down to a one off.

A few things to note.

1. Looking at the database I don't think the user should of got this message. He does have several websites, but there is only one Warehouse account so there is no ambiguity.
2. Removing his attachment to the Warehouse (clearing the Indicia Warehouse ID from his Drupal account) and then saving again, reattaches the account to 177 immediately without problem.
3. Signing up with one of my email address that has a similar situation with lots of websites didn't cause this message and was fine.
4. I think would be caused by the Warehouse anyway, it may have been that it was busy at the point the issue occurred.

Closing based on this evidence, please re-open if further evidence of an ongoing issue comes to light.

**Closed as completed by andrewvanbreda** 2021-06-08 09:52 UTC
Labels: bug
