### ISSUE TITLE
Move site from Drupal 8 to Drupal 9

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#131] opened 2021-09-17 09:21 UTC
Hi  @BirenRathod @CCarvell @kitenetter 

Thought I would open an issue for the move so that details can be stored here rather than lost in emails.

So far I have done a check of the code to make sure it should work in Drupal 9.
No alterations to the existing code were identified.
However the new checking/verification pages will need some alteration. These are not deployed yet so this isn't a problem.

I did do some limited practical tests on the Drupal 9 test site. The site past inspection apart from 3 observations

1. Lots of translations were not working on the pages. Biren has said this isn't a genuine problem, but because that Drupal 9 site hasn't been attached to the UKPoMS name yet, so the final version will be unaffected.

2.
The recent grid width CSS alteration was missing on the Drupal 9 test site. I think Biren has corrected this one already.

3.
A slight oddity was detected during registration (I think Biren may have already looked at fixing this).
After using the one-time login and setting password and saving, it confusingly tells you to change your password.
This is the message...
"You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password.
The changes have been saved."
So it continues to tell the user to change their password even after save.

The Drupal 8 version doesn't have this problem, it just says 
"The changes have been saved." after the password save.

Maybe Biren will be able to confirm.

Note to all: The Drupal 9 test site is at this address.
https://test-ceh-ukpoms.pantheonsite.io

**Comment by BirenRathod** [comment] 2021-09-17 09:29
Thanks, @andrewvanbreda. As you already mentioned my comments, we are good to go for Drupal 9 Migration. this is only site left for me to migrate. 
@kitenetter Have you sorted out the downtime regarding this? please do so. I believe October & November will get more busy, so better to do next week.

**Comment by CCarvell** [comment] 2021-09-17 10:59
@BirenRathod - @kitenetter is on leave and back Monday 20th.
Since Andy noted that Drupal 8 is coming to end of life 2nd November I was wondering if we could wait until PoMS surveys have finished at the end of September, as Biren noted the migration takes 1 hour to 12 hours max.

BUT if it has to be next week, then perhaps we could say Wednesday? That way Martin can confirm on Monday and has time to maybe put a note out on the PoMS Twitter account that the website and data forms will be down for a few hours on Weds?

**Comment by BirenRathod** [comment] 2021-09-17 12:50
@CCarvell Yes, Wednesday will be perfect once @kitenetter confirmed that.

**Comment by kitenetter** [comment] 2021-09-20 08:20
Okay, I will put out a message for Wednesday.

**Comment by BirenRathod** [comment] 2021-09-20 08:31
@kitenetter yes, please. thanks. I assume you are going to put message on website too. I will put down website after 12:00 pm.

**Comment by kitenetter** [comment] 2021-09-20 08:33
@BirenRathod do you mean it will be down from mid-day on Wednesday 22 September?

**Comment by BirenRathod** [comment] 2021-09-20 08:35
@kitenetter Yes.

**Comment by BirenRathod** [comment] 2021-09-20 09:21
@andrewvanbreda Just see above for your info.

**Comment by andrewvanbreda** [comment] 2021-09-20 10:22
@BirenRathod Yes that is fine, won't really affect me as I just won't work on the site that day.

**Comment by andrewvanbreda** [comment] 2021-09-21 11:28
Just for the record, I noticed the Species Grid translations were not appearing (actually the rows were completely empty).

This was fixed by 
Using this  line in dynamic.php
$html .= call_user_func(array(self::$called_class, $method), $auth, $args, $tabalias, array_merge(['extraParams'=>$auth['read']], $options));

instead of this
$html .= call_user_func(array(self::$called_class, $method), $auth, $args, $tabalias, array_merge($defAttrOptions, $options));

This was already present on the Drupal 8 site

**Comment by andrewvanbreda** [comment] 2021-09-23 09:34
@BirenRathod @kitenetter 
I have added translation for the help text and labels on the Welsh Fit Count data entry form for the Drupal 9 site.
The termlists translation won't work unless the User Interface Translation problem is fixed.
Note there is some old code (that is no longer needed because of a bug fix) that could be adapted that used to force translation of the species grid, am sure that could be changed for the whole page, but would need some extra budget....maybe a few hours work.

**Comment by andrewvanbreda** [comment] 2021-09-23 09:44
@BirenRathod 
It is probably a good idea to leave the Drupal 8 test running for now as it maybe useful for fixing the translation issue.

**Comment by BirenRathod** [comment] 2021-09-23 09:48
@andrewvanbreda My recommendation is you don't need to use drupal 8 test env. instead you can use live env of Drupal 8. It will will be available soon one propagation process finished completely. Here is the URL of that -> http://live-ceh-poms.pantheonsite.io/
Although test & live env of Drupal 8 will be available till End of Oct. After that I have to decommission them.

**Comment by CCarvell** [comment] 2021-09-23 09:52
@andrewvanbreda if there is a clear (near-guaranteed) fix to this Welsh translation issue that you have identified, then I think we should sort it out asap. I have already alerted our Welsh Gov funder (she's also a PoMS volunteer) and she is keen that we meet our objectives of treating the English and Welsh equally, but is OK with the site having gone back to live as it is.

Could you please send a short 'quote' for the few hours you anticipate needing for this work, with your rate and cost.
I am tempted to ask WG if they would consider funding it separately as we have already soaked up considerable extra cost for translation work than originally budgeted, plus we are effectively providing @BirenRathod s time on the website for free on this project. It's worth asking, but if not then I am sure we can fund the work needed somehow.

**Comment by BirenRathod** [comment] 2021-09-23 09:54
> @BirenRathod @kitenetter
> I have added translation for the help text and labels on the Welsh Fit Count data entry form for the Drupal 9 site.
> The termlists translation won't work unless the User Interface Translation problem is fixed.
> Note there is some old code (that is no longer needed because of a bug fix) that could be adapted that used to force translation of the species grid, am sure that could be changed for the whole page, but would need some extra budget....maybe a few hours work.

When you say "The termlists translation won't work unless the User Interface Translation problem is fixed." . This is not something we should do as this feature been introduced by one of Drupal contributed module. 

Also, about extra budget for fixing species grid bit is something I could not comment on. It is definitely to consider for @CCarvell to decide.

**Comment by andrewvanbreda** [comment] 2021-09-23 12:54
@BirenRathod 
That is fine. I wasn't intending to actively work on it. But it is worth leaving until the language is fixed.

@CCarvell
No it isn't a near-guarantee. I will have to do a test, then I can send a quote. I would hope it works.

However what I will do is see if John has seen this happen before first as really we could do with the translation module working.

I have also had to soak up overrun on the project that I hadn't originally anticipated.
I think that a lot of the trouble was that I hadn't realised some of the forms wouldn't have a translation (and I wouldn't of known that was going to cause difficulty anyway).
But actually that mixture made the translation very difficult.

**Comment by andrewvanbreda** [comment] 2021-09-23 13:51
@BirenRathod 
I have spoken to John, and he remind me of an option to check that I had forgotten about.
I think this line is missing from the helper_config (actually I think the helper_config file isn't present)

public static $delegate_translation_to_hostsite = TRUE;

I think this will fix it. I dunno if you just want to copy over the old helper_config from the Drupal 8 site, or whether you want me to commit it into Pantheon.
Anyway, let me know, but am almost certain that is the issue.

**Comment by BirenRathod** [comment] 2021-09-23 13:54
@andrewvanbreda Yes, that has not been added as I copied drupal 8 version of git on to ceh-ukpoms repository not from ceh-poms repository. Please commit onto pantheon of ceh-ukpoms, so If I update iform module in future, I will check first and copy that.

**Comment by andrewvanbreda** [comment] 2021-09-23 14:17
@kitenetter @CCarvell @BirenRathod 
Language problem fixed.
Not the new configuration version of that configuration file for the website has an extra option 
"upload_max_filesize = '4M'"
I didn't remove it, as it might be required for the later version of the code the site is now running.
However it could theoretically impact the size of images people can upload, we can increase if needed.

Please close this issue once you are happy with the way the new Drupal 9 site is running.

**Comment by BirenRathod** [comment] 2021-09-23 14:20
Fantastic @andrewvanbreda. Upload file size is fine.

**Comment by kitenetter** [comment] 2021-09-23 14:22
Many thanks @andrewvanbreda - I will do final checks and close the issue tomorrow.

**Comment by andrewvanbreda** [comment] 2021-09-30 20:43
@kitenetter @BirenRathod 
Hi, 
When I was looking at your question from this morning just now, I just noticed the Create Account link s now very small, it wasn't even obvious to me at first.
That is a theme issue, so am just raising it, you'll need to ask Biren or Steve to have a look.

**Closed as completed** 2024-06-18 12:30 UTC
